# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: myAgentPool
variables:
  azureServiceConnectionId: 'myServiceConnection'
  webAppName: 'mywebapp1988123'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: BuildJob
      pool: myAgentPool
      steps:
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          python3.10 -m pip install -r requirements.txt
        workingDirectory: $(projectRoot)
        displayName: 'Step - Install Requirements'
        
      - task: ArchiveFiles@2
        displayName: 'Step - Archive Files'
        inputs:
          rootFolderOrFile: '$(projectRoot)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
        
      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: 'Step - Upload Package'
        artifact: drop